/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Asanka
 */
public final class book extends javax.swing.JFrame {
Locale locale;
    /**
     * Creates new form book
     */
    
    String name;
    String author;
    String donator;
    int id;
    String barcode;
     boolean close=false;
     
    public book(String a,String b,String c,String d,int e,Locale locale) {
    
           //initlocale();
        initComponents();
            try {
             initlocale();
        } catch (Exception eg) {
            System.out.println(eg);
        }
            
            
            
            
   
        setLocationRelativeTo(null);
        jLabel_date.setText(today);
        jLabel_time.setText(time);
        
        name=a;
        author=b;
        donator=c;
        barcode=d;
        id=e;
    
        view();
        
       
    }

    
    
    
 

   
    public void view(){
        
            jLabel_name.setText(name);
            jLabel_author.setText(author);
            jLabel_donator.setText(donator);
            jLabel_barcode.setText(barcode);
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_author = new javax.swing.JLabel();
        jLabel_donator = new javax.swing.JLabel();
        jLabel_barcode = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_recever = new javax.swing.JTextField();
        jTextField_reg = new javax.swing.JTextField();
        jLabel_date = new javax.swing.JLabel();
        jLabel_time = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("bundles/bookBundle"); // NOI18N
        jLabel1.setText(bundle.getString("book.jLabel1.text")); // NOI18N
        jLabel1.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText(bundle.getString("book.jLabel3.text")); // NOI18N
        jLabel3.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText(bundle.getString("book.jLabel4.text")); // NOI18N
        jLabel4.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText(bundle.getString("book.jLabel5.text")); // NOI18N
        jLabel5.setOpaque(true);

        jLabel_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name.setText(bundle.getString("book.jLabel_name.text")); // NOI18N
        jLabel_name.setOpaque(true);

        jLabel_author.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_author.setText(bundle.getString("book.jLabel_author.text")); // NOI18N
        jLabel_author.setOpaque(true);

        jLabel_donator.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_donator.setText(bundle.getString("book.jLabel_donator.text")); // NOI18N
        jLabel_donator.setOpaque(true);

        jLabel_barcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_barcode.setText(bundle.getString("book.jLabel_barcode.text")); // NOI18N
        jLabel_barcode.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_name, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addComponent(jLabel_author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_donator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_barcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_name))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_author))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_donator))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_barcode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("book.jPanel2.border.title"))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText(bundle.getString("book.jLabel13.text")); // NOI18N
        jLabel13.setOpaque(true);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText(bundle.getString("book.jLabel14.text")); // NOI18N
        jLabel14.setOpaque(true);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText(bundle.getString("book.jLabel15.text")); // NOI18N
        jLabel15.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText(bundle.getString("book.jLabel16.text")); // NOI18N
        jLabel16.setOpaque(true);

        jTextField_recever.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextField_reg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_date.setText(bundle.getString("book.jLabel_date.text")); // NOI18N
        jLabel_date.setOpaque(true);

        jLabel_time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_time.setText(bundle.getString("book.jLabel_time.text")); // NOI18N
        jLabel_time.setOpaque(true);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText(bundle.getString("book.jLabel17.text")); // NOI18N
        jLabel17.setOpaque(true);

        jTextField_phone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_recever)
                    .addComponent(jTextField_reg)
                    .addComponent(jLabel_date)
                    .addComponent(jLabel_time)
                    .addComponent(jLabel17)
                    .addComponent(jTextField_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_recever, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_date)
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_time)
                .addGap(77, 77, 77))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, -1, 358));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText(bundle.getString("book.jLabel6.text")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.jpg"))); // NOI18N
        jButton1.setText(bundle.getString("book.jButton1.text")); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, 110, 36));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        jButton3.setText(bundle.getString("book.jButton3.text")); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 590, 110, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/approved.png"))); // NOI18N
        jButton2.setText(bundle.getString("book.jButton2.text")); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1009, 590, 120, 36));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/123 copy.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 664));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private void initlocale() {
              ResourceBundle bundle=ResourceBundle.getBundle("bundles/bookBundle", locale);
    
        jLabel1.setText(bundle.getString("book.jLabel1.text")); // NOI18N


        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText(bundle.getString("book.jLabel3.text")); // NOI18N


        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText(bundle.getString("book.jLabel4.text")); // NOI18N


        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText(bundle.getString("book.jLabel5.text")); // NOI18N


        jLabel_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name.setText(bundle.getString("book.jLabel_name.text")); // NOI18N


        jLabel_author.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_author.setText(bundle.getString("book.jLabel_author.text")); // NOI18N


        jLabel_donator.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_donator.setText(bundle.getString("book.jLabel_donator.text")); // NOI18N


        jLabel_barcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_barcode.setText(bundle.getString("book.jLabel_barcode.text")); // NOI18N


     

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("book.jPanel2.border.title"))); // NOI18N


        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText(bundle.getString("book.jLabel13.text")); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText(bundle.getString("book.jLabel14.text")); // NOI18N


        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText(bundle.getString("book.jLabel15.text")); // NOI18N
        jLabel15.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText(bundle.getString("book.jLabel16.text")); // NOI18N
      


        jLabel_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_date.setText(bundle.getString("book.jLabel_date.text")); // NOI18N
   
        jLabel_time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_time.setText(bundle.getString("book.jLabel_time.text")); // NOI18N


        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText(bundle.getString("book.jLabel17.text")); // NOI18N
 

       
      

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText(bundle.getString("book.jLabel6.text")); // NOI18N


        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.jpg"))); // NOI18N
        jButton1.setText(bundle.getString("book.jButton1.text")); // NOI18N
   
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancel.png"))); // NOI18N
        jButton3.setText(bundle.getString("book.jButton3.text")); // NOI18N
   


        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/approved.png"))); // NOI18N
        jButton2.setText(bundle.getString("book.jButton2.text")); // NOI18N
   
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/123 copy.jpg"))); // NOI18N
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String sql="insert into lender (id,receiver,reciever_name,date,time,phone)values('"+id+"','"+jTextField_reg.getText()+"','"+jTextField_recever.getText()+"','"+jLabel_date.getText()+"','"+jLabel_time.getText()+"','"+jTextField_phone.getText()+"')";
       Insert_Update(sql);
       String sql2="update book set status='OUT STOCK' where id='"+id+"'";
       Insert_Update(sql2);
       
        JOptionPane.showMessageDialog(rootPane, " Thank you  ", "Information", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        new Home(locale).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.dispose();
        new Home(locale).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      clear();
    }//GEN-LAST:event_jButton3ActionPerformed

      String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    String time = new SimpleDateFormat("HH:mm:ss").format(Calendar.getInstance().getTime());
    
     public void Insert_Update(String query) {

        try {

            Statement stmt;
            Connection con = DBconnect.connectdb();
            stmt = con.createStatement();

            stmt.executeUpdate(query);

            

        } catch (SQLException ex) {
            
        }

    }
    
    public void clear(){
    
    jTextField_phone.setText("");
     jTextField_recever.setText("");
      jTextField_reg.setText("");
      jTextField_recever.requestFocus();
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new book(locale).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_author;
    private javax.swing.JLabel jLabel_barcode;
    private javax.swing.JLabel jLabel_date;
    private javax.swing.JLabel jLabel_donator;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_time;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_phone;
    private javax.swing.JTextField jTextField_recever;
    private javax.swing.JTextField jTextField_reg;
    // End of variables declaration//GEN-END:variables

 
}
