/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static java.util.Calendar.DATE;
import java.util.Date;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Asanka
 */
public class Home extends javax.swing.JFrame {
    
    String barcode;
    int id;
Locale locale;
ResourceBundle bundle ;
   // ResourceBundle rb;
    /**
     * Creates new form managebook
     * @param locale
     */
    public Home(Locale locale) {
         bundle = ResourceBundle.getBundle("bundles/homebundle", locale);
   //  rb=ResourceBundle.getBundle("homebundle",locale);
      
        initComponents();
          initlocale(bundle);
        setLocationRelativeTo(null);
        jTextField1.requestFocus();
    }

    Home() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("bundles/homebundle"); // NOI18N
        jTextField2.setText(bundle.getString("Home.jTextField2.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 643, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("Home.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 643, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText(bundle.getString("Home.jLabel9.text")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(bundle.getString("Home.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 480, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/setting.png"))); // NOI18N
        jButton1.setText(bundle.getString("Home.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 610, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/123 copy.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 664));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
      private void initlocale(ResourceBundle bundle) {
        //  ResourceBundle  bundle=ResourceBundle.getBundle("bundles/homebundle");
   jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/123 copy.jpg"))); // NOI18N
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/setting.png"))); // NOI18N
       jLabel2.setText(bundle.getString("Home.jLabel2.text")); // NOI18N
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
            //  java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("bundles/homebundle"); // NOI18N
        jTextField2.setText(bundle.getString("Home.jTextField2.text")); // NOI18N



        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N



        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
   
        jLabel1.setText(bundle.getString("Home.jLabel1.text")); // NOI18N
   

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N

        jLabel9.setText(bundle.getString("Home.jLabel9.text")); // NOI18N
  
        
       
    }
    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        if (evt.getKeyChar() == 10 || evt.getKeyChar() == 13) {
           
          
String barcode=null;
                barcode=  jTextField1.getText();
        String sql = "select * from book where barcode ='"+barcode+"' and status='IN STOCK'";

        Statement st;
        ResultSet rs;

        try {
            Connection con = DBconnect.connectdb();
            st = con.createStatement();
            rs = st.executeQuery(sql);

            if (rs.next()) {
               
                String name = rs.getString("name");
                String author = rs.getString("author");
                String donator = rs.getString("donater");
                int id = rs.getInt("id");

                new book(name, author, donator, barcode, id,locale).setVisible(true);
                this.dispose();

            } else {
 
                String sql2 = "select * from book where barcode ='"+barcode+"' and status='OUT STOCK'";
                Statement st1;
                ResultSet rs1;
                st1 = con.createStatement();
                rs1 = st1.executeQuery(sql2);

                if (rs1.next()) {
                     

                    int bookid = rs1.getInt("id");
                    
                    String query="update book set status='IN STOCK' where id='"+bookid+"'";
                    Insert_Update(query);
                    String query2="delete from lender where id='"+bookid+"'";
                    Insert_Update(query2);
                    JOptionPane.showMessageDialog(rootPane, " Thank you using public library ", "Information", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    new Home(locale).setVisible(true);

                }
                else{
                JOptionPane.showMessageDialog(rootPane, " Data not found ", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            }
             // 
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e );
        }

                 
            
            
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  this.dispose();
//  new login(locale).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
 
    
        public void Insert_Update(String query) {

        try {

            Statement stmt;
            Connection con = DBconnect.connectdb();
            stmt = con.createStatement();

            stmt.executeUpdate(query);

            

        } catch (SQLException ex) {
            
        }

    }
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

  
}
